build:
  nodes:
    analysis:
      project_setup:
        override: true
      tests:
        override: [php-scrutinizer-run]
    test:
      tests:
        override:
          - command: ./bin/phpunit
  services:
    mysql: 5.7

  environment:
    variables:
      APP_ENV: test
      APP_DEBUG: 1
      SHELL_INTERACTIVE: 0

  project_setup:
    before:
      - php bin/console doctrine:database:create -n
      - php bin/console doctrine:migrations:migrate -n
      - export JWT_PASSPHRASE=$(openssl rand -base64 32);
      - mkdir -p config/jwt;
      - openssl genpkey -out config/jwt/private.pem -aes256 -algorithm rsa -pkeyopt rsa_keygen_bits:4096s -pass "pass:$JWT_PASSPHRASE";
      - openssl pkey -in config/jwt/private.pem -out config/jwt/public.pem -pubout -passin "pass:$JWT_PASSPHRASE";
