build:
  nodes:
    analysis:
      project_setup:
        override: true
      tests:
        override: [php-scrutinizer-run]
  services:
    mysql: 5.7

  environment:
    variables:
      APP_ENV: test
      APP_DEBUG: 1
      SHELL_INTERACTIVE: 0

  project_setup:
    before:
      - php bin/console doctrine:database:create
      - php bin/console doctrine:migrations:migrate

tools:
  external_code_coverage:
    timeout: 600
    runs: 3
