build:
  services:
    mysql: 5.7

  environment:
    variables:
      APP_ENV: test
      APP_DEBUG: 1
      SHELL_INTERACTIVE: 0

  project_setup:
    before:
      - php bin/console doctrine:database:create -n
      - php bin/console doctrine:migrations:migrate -n
