language: php

env:
  global:
    - APP_ENV=test
    - APP_DEBUG=1
    - NODE_ENV=test
    - DATABASE_NAME=solidplan_test

cache:
  yarn: true
  directories:
    - $HOME/.composer/cache
    - node_modules

services:
  - mysql

before_install:
  - composer self-update
  - mysql -e "create database $DATABASE_NAME;"

install:
  - composer install -n

before_script:
  - export JWT_PASSPHRASE=$(openssl rand -base64 32);
  - mkdir -p config/jwt;
  - openssl genpkey -out config/jwt/private.pem -aes256 -algorithm rsa -pkeyopt rsa_keygen_bits:4096s -pass "pass:$JWT_PASSPHRASE";
  - openssl pkey -in config/jwt/private.pem -out config/jwt/public.pem -pubout -passin "pass:$JWT_PASSPHRASE";
  - php bin/console doctrine:migrations:migrate -n

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: 7.4snapshot
  include:
    - php: 7.1
      script:
        - composer validate
        - bin/phpunit --coverage-clover build/logs/clover.xml
        - ./vendor/bin/phpstan analyse ./src -vvv --level=max -c phpstan.neon
      after_script:
        - travis_retry wget https://scrutinizer-ci.com/ocular.phar
        - travis_retry php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
        - travis_retry php ./vendor/bin/php-coveralls -v
    - php: 7.2
      script: bin/phpunit
    - php: 7.3
      script: bin/phpunit
    - php: 7.4snapshot
      script: bin/phpunit
    - node_js: "12"
      services: null
      before_install:
          - nvm install 12
          - nvm use 12
      install:
        - yarn
      before_script: skip
      script: yarn run test
